# Generated by Django 5.0 on 2023-12-27 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product_id", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("price", models.IntegerField()),
                (
                    "manufacturer",
                    models.CharField(
                        choices=[
                            ("Asus", "Asus"),
                            ("Coolermaster", "Coolermaster"),
                            ("Gigabyte", "Gigabyte"),
                            ("LianLi", "LianLi"),
                            ("Antec", "Antec"),
                            ("Corsair", "Corsair"),
                        ],
                        default="Asus",
                        max_length=50,
                    ),
                ),
                ("stock", models.BooleanField(default=False)),
                ("mf_page", models.URLField()),
                (
                    "image",
                    models.ImageField(
                        default="default.png", upload_to="product-images"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HumanResources",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("person_id", models.CharField(max_length=9, unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("birth_date", models.DateField()),
                ("city", models.CharField(max_length=50)),
                ("street", models.CharField(max_length=50, null=True)),
                ("building_number", models.IntegerField(null=True)),
                ("apartment_number", models.IntegerField(null=True)),
                ("cellphone_number", models.CharField(max_length=10)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shop.product",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Processor", "Processor"),
                            ("GraphicsCard", "Graphics Card"),
                            ("Motherboard", "Motherboard"),
                            ("Memory", "Memory"),
                            ("Cooler", "Cooler"),
                            ("Storage", "Storage"),
                            ("Power Supply", "Power Supply"),
                            ("Case", "Case"),
                            ("Keyboard", "Keyboard"),
                            ("Mouse", "Mouse"),
                            ("Monitor", "Monitor"),
                        ],
                        default="Processor",
                        max_length=50,
                    ),
                ),
            ],
            bases=("shop.product",),
        ),
        migrations.CreateModel(
            name="Computer",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shop.product",
                    ),
                ),
            ],
            bases=("shop.product",),
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "humanresources_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shop.humanresources",
                    ),
                ),
                ("membership", models.BooleanField(default=False)),
                ("ms_points", models.IntegerField()),
            ],
            bases=("shop.humanresources",),
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "humanresources_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shop.humanresources",
                    ),
                ),
                (
                    "work_branch",
                    models.CharField(
                        choices=[("Beer Sheva", "Beer Sheva"), ("Eilat", "Eilat")],
                        default="Beer Sheva",
                        max_length=50,
                    ),
                ),
                ("job_title", models.CharField(max_length=50)),
                ("workstart_date", models.DateField()),
            ],
            bases=("shop.humanresources",),
        ),
        migrations.CreateModel(
            name="ComputerInternal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField()),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.component"
                    ),
                ),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.computer"
                    ),
                ),
            ],
            options={
                "unique_together": {("computer", "component")},
            },
        ),
        migrations.AddField(
            model_name="computer",
            name="components",
            field=models.ManyToManyField(
                through="shop.ComputerInternal", to="shop.component"
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("Credit Card", "Credit Card"), ("Cash", "Cash")],
                        default="Credit Card",
                        max_length=50,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("products", models.ManyToManyField(to="shop.product")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.customer"
                    ),
                ),
            ],
        ),
    ]
